on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Java 22.0.1 (Your specific version)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '22.0.1'   # Exact version of Java you have (22.0.1)
      
      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      # Build APK
      - run: flutter build apk --release --split-per-abi
      
      # Build iOS IPA
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          cd Payload
          zip -r ../app.ipa .
      
      # Push to Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk,
            build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

